services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: quotesdb
      POSTGRES_PASSWORD: localpassword123
      POSTGRES_DB: quotesdb
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - quotes-network

networks:
  quotes-network:
    driver: bridge

volumes:
  db_data: